<?php

/**
 * @file
 * Y-LB Blocks Branch Social Links submodule.
 */

 use Drupal\node\NodeInterface;

/**
 * Implements hook_theme().
 */
function lb_branch_amenities_blocks_theme($existing, $type, $theme, $path) {
  return [
    'block__lb_branch_amenities_blocks' => [
      'base hook' => 'block',
      'template' => 'block--lb-branch-amenities-blocks',
    ],
    'field__block_content__field_section_title__lb_branch_amenities_blocks' => [
      'base hook' => 'field',
      'template' => 'field--block-content--field-section-title--lb-branch-amenities-blocks',
    ],
    'field__block_content__field_section_subtitle__lb_branch_amenities_blocks' => [
      'base hook' => 'field',
      'template' => 'field--block-content--field-section-subtitle--lb-branch-amenities-blocks',
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lb_branch_amenities_blocks_preprocess_block__lb_branch_amenities_blocks(&$variables) {
  $variables['block_content'] = $variables['elements']['content']['#block_content'];
  $node = Drupal::routeMatch()->getParameter('node');
  if (!$node) {
    $inlineBlock = Drupal::service('inline_block.usage');
    $block = $variables['content']['#block_content'];
    $result = $inlineBlock->getUsage($block->id());
    if ($result && ($nodeId = $result->layout_entity_id)) {
      $entityTypeManager = Drupal::service('entity_type.manager');
      $node = $entityTypeManager->getStorage('node')->load($nodeId);
    }
  }

  if (!$node instanceof NodeInterface) {
    return;
  }

  if ($node->bundle() === 'facility'
    && $node->hasField('field_facility_loc')
    && !$node->get('field_facility_loc')->isEmpty()
  ) {
    $entities = $node->get('field_facility_loc')->referencedEntities();
    unset($node);
    $node = reset($entities);
  }

  if ($node->hasField('field_location_amenities') &&
    ($amenitiesField = $node->get('field_location_amenities')) &&
    ($terms = $amenitiesField->referencedEntities())) {

    $variables['content']['field_location_amenities'] = [];
    foreach ($terms as $term) {
      $lang_code = \Drupal::service('language_manager')->getCurrentLanguage()->getId();
      if ($term->hasTranslation($lang_code)) {
        $term = $term->getTranslation($lang_code);
      }
      $variables['content']['field_location_amenities'][] = $term->getName();
    }
  }

  if ($node->hasField('field_location_amenities_closed') &&
    ($amenitiesField = $node->get('field_location_amenities_closed')) &&
    ($terms = $amenitiesField->referencedEntities())) {

    $variables['content']['field_location_amenities_closed'] = [];
    foreach ($terms as $term) {
      $variables['content']['field_location_amenities_closed'][] = $term->getName();
    }
  }
}
