<?php

/**
 * @file
 *  Contains install and update functions for the Layout Builder Accordions module.
 */

use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Add "Is FAQ?" field to enable FAQPage schema on accordions.
 */
function lb_accordion_update_9001() {
  $path = \Drupal::service('extension.list.module')->getPath('lb_accordion') . '/config/outdated/2.0.2';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'core.entity_form_display.block_content.lb_accordion.default',
    'core.entity_view_display.block_content.lb_accordion.default',
    'field.field.block_content.lb_accordion.field_is_faq',
    'field.storage.block_content.field_is_faq'
  ]);
}

/**
 * Import config to create 'accordion_item' sub block for 'lb_accordion' block.
 */
function lb_accordion_update_9002() {
  $path = \Drupal::service('extension.list.module')->getPath('lb_accordion') . '/config/outdated/2.0.2';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'block_content.type.accordion_item',
    'core.entity_form_display.block_content.accordion_item.default',
    'core.entity_view_display.block_content.accordion_item.default',
    'field.field.block_content.accordion_item.body',
    'field.field.block_content.accordion_item.field_title',
    'field.field.block_content.lb_accordion.field_block_item',
    'field.storage.block_content.field_block_item',
  ]);
}

/**
 * Migrate content from 'lb_accordion' paragraph to 'accordion_item' block.
 */
function lb_accordion_update_9003(&$sandbox) {
  /** @var \Drupal\Core\Entity\EntityTypeManager $entityTypeManager */
  $entityTypeManager = \Drupal::entityTypeManager();
  $storageParagraph = $entityTypeManager->getStorage('paragraph');
  $storageBlock = $entityTypeManager->getStorage('block_content');

  if (!isset($sandbox['progress'])) {
    $sandbox['progress'] = 0;
    $sandbox['data'] = [
      'paragraphs' => $storageParagraph->loadByProperties(['type' => 'lb_accordion_item']),
      'blocks' => []
    ];
    // Group paragraphs by parent id.
    foreach ($sandbox['data']['paragraphs'] as $id => $paragraph) {
      $sandbox['data']['blocks'][$paragraph->get('parent_id')->value][] = $id;
    }
    $sandbox['total'] = count($sandbox['data']['blocks']);
  }

  $blocks = array_slice($sandbox['data']['blocks'], $sandbox['progress'], 5, true);


  foreach ($blocks as $parentId => $paragraphIds) {
    $newBlockIds = [];

    foreach ($paragraphIds as $paragraphId) {
      $paragraph = $sandbox['data']['paragraphs'][$paragraphId];
      $fieldBody = $paragraph->get('field_body')->getValue()[0];

      // Create new 'accordion_item' sub block with content from paragraph
      $block = $storageBlock->create([
        'type' => 'accordion_item',
        'body' => [
          'value' => $fieldBody['value'] ?? '',
          'format' => $fieldBody['format'] ?? 'full_html',
        ],
        'field_title' => $paragraph->get('field_title')->value ?? '',
      ]);

      $block->save();
      $newBlockIds[] = $block->id();
      $paragraph->delete();
    }

    // Load parent block and set new sub block.
    /** @var \Drupal\block_content\Entity\BlockContent $parentBlock */
    if (($parentBlock = $storageBlock->load($parentId)) && $parentBlock->bundle() === 'lb_accordion') {
      $parentBlock->set('field_block_item', $newBlockIds)->save();
    }
    $sandbox['progress']++;
  }

  $sandbox['#finished'] = empty($sandbox['total']) ? 1 : $sandbox['progress'] / $sandbox['total'];
}

/**
 * Remove 'lb_accordion' paragraph config
 */
function lb_accordion_update_9004() {
  $path = \Drupal::service('extension.list.module')->getPath('lb_accordion') . '/config/outdated/2.0.2';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');

  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'core.entity_form_display.block_content.lb_accordion.default',
    'core.entity_view_display.block_content.lb_accordion.default',
  ]);

  $configsToDelete = [
    'paragraphs.paragraphs_type.lb_accordion_item',
    'core.entity_form_display.paragraph.lb_accordion_item.default',
    'core.entity_view_display.paragraph.lb_accordion_item.default',
  ];

  $configFactory = \Drupal::configFactory();
  foreach ($configsToDelete as $config) {
    $configFactory->getEditable($config)->delete();
  }

  FieldConfig::loadByName('paragraph', 'lb_accordion_item', 'field_title')?->delete();
  FieldConfig::loadByName('paragraph', 'lb_accordion_item', 'field_body')?->delete();
  FieldConfig::loadByName('block_content', 'lb_accordion', 'field_entity_reference_paragraph')?->delete();

  FieldStorageConfig::loadByName('block_content', 'field_entity_reference_paragraph')?->delete();
}

/**
 * Rename label "field_block_item" field
 */
function lb_accordion_update_9005() {
  $path = \Drupal::service('extension.list.module')->getPath('lb_accordion') . '/config/optional';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'field.field.block_content.lb_accordion.field_block_item',
  ]);
}

/**
 * Add "field_section_subtitle" to accordion
 */
function lb_accordion_update_9006() {
  $path = \Drupal::service('extension.list.module')->getPath('lb_accordion') . '/config/outdated/2.1.4';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'core.entity_form_display.block_content.lb_accordion.default',
    'core.entity_view_display.block_content.lb_accordion.default',
    'field.field.block_content.lb_accordion.field_section_subtitle',
    'field.storage.block_content.field_section_subtitle',
  ]);
}
