<?php

/**
 * @file
 * Y-LB Blocks Accordion submodule.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

 /**
 * Implements hook_help().
 */
function lb_accordion_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lb_accordion module.
    case 'help.page.lb_accordion':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Accordion for Layout Builder.') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function lb_accordion_theme($existing, $type, $theme, $path) {
  return [
    'block__lb_accordion' => [
      'base hook' => 'block',
      'template' => 'block--lb-accordion',
    ]
  ];
}

/**
 * Implements hook_block_view_alter().
 * Requires https://www.drupal.org/project/drupal/issues/3292520
 */
function lb_accordion_block_view_inline_block_alter(array &$build, \Drupal\Core\Block\BlockPluginInterface $block)
{
  if ($block->getPluginId() == 'inline_block:lb_accordion' && !$build["#in_preview"]) {
    $is_faq = $build["content"]["#block_content"]->field_is_faq->value;

    // If this Accordion isn't a FAQ then bail.
    if (!$is_faq) { return; }

    $faq_items = [];
    $items = $build["content"]["#block_content"]->field_block_item->referencedEntities();

    foreach ($items as $item) {
      $faq_items[] = [
        '@type' => 'Question',
        'name' => $item->field_title->value,
        'acceptedAnswer' => [
          '@type' => 'Answer',
          'text' => $item->body->value,
        ]
      ];
    }

    if (!empty($faq_items)) {
      $faq_schema = [
        '@context' => stripslashes('https://schema.org'),
        '@graph' => [
          [
            '@type' => 'FAQPage',
            'mainEntity' => $faq_items,
          ]
        ]
      ];
      $description = [
        '#tag' => 'script',
        '#attributes' => [
          'type' => 'application/ld+json',
        ],
        '#value' => json_encode($faq_schema, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT),
      ];
      $build['#attached']['html_head'][] = [$description, 'faq_schema'];
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for block entities.
 */
function lb_accordion_block_content_presave(EntityInterface $block) {
  if ($block->bundle() === 'accordion_item') {
     $block->setInfo($block->get('field_title')->value);
  }
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function lb_accordion_inline_entity_form_entity_form_alter(array &$entity_form, FormStateInterface $form_state) {
  $entity = $entity_form['#entity'];
  if ($entity->bundle() === 'accordion_item' && !empty($form_state->getUserInput()['settings']['block_form']['field_block_item']['form'])) {
    $form = $form_state->getUserInput()['settings']['block_form']['field_block_item']['form'];
    if (isset($form['inline_entity_form'])) {
      $resultForm = reset($form['inline_entity_form']['entities'])['form'];
    }
    else {
      $resultForm = reset($form);
    }
    $entity->setInfo($resultForm['field_title']['0']['value']);
  }
}

/**
 * Implements hook_preprocess_block().
 */
function lb_accordion_preprocess_block__lb_accordion(&$variables) {
  $variables['block_content'] = $variables['elements']['content']['#block_content'];
}
