<?php
/**
 * @file
 * Install, update and uninstall functions for the LB Partners Blocks module.
 */

/**
 * Add a Tier wrapper for the partners list.
 */
function lb_partners_blocks_update_91001() {
  $path = \Drupal::service('extension.list.module')->getPath('lb_partners_blocks') . '/config/optional';
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'block_content.type.partners_tier',
    'field.storage.block_content.field_partners_items',
    'field.storage.block_content.field_title',
    'field.field.block_content.lb_partners.field_partners',
    'field.field.block_content.partners_tier.field_partners_items',
    'field.field.block_content.partners_tier.field_title',
    'core.entity_form_display.block_content.partners_tier.default',
    'core.entity_view_display.block_content.partners_tier.default',
  ]);
}

/**
 * Migrate existing blocks to blocks with Tier wrapper.
 */
function lb_partners_blocks_update_91002(&$sandbox) {
  /** @var \Drupal\Core\Entity\EntityTypeManager $entity_type_manager */
  $entity_type_manager = \Drupal::entityTypeManager();
  $storage = $entity_type_manager->getStorage('block_content');
  // Load all lb_partners blocks and count them.
  if (!isset($sandbox['progress'])) {
    $sandbox['progress'] = 0;
    $sandbox['data'] = [
      'blocks' => $storage->loadByProperties(['type' => 'lb_partners']),
    ];

    $sandbox['total'] = count($sandbox['data']['blocks']);
  }

  $blocks = array_slice($sandbox['data']['blocks'], $sandbox['progress'], 5, TRUE);

  foreach ($blocks as $lb_partners_block) {
    // Prepare an array of partner items.
    $lb_partners_items_block_ids = array_map(function ($partners_item) {
      return ['target_id' => $partners_item->id()];
    }, $lb_partners_block?->field_partners?->referencedEntities());
    // Create a new partners_tier block.
    $tier_block = $storage->create([
      'type' => 'partners_tier',
    ]);
    $tier_block->set('field_title', '');
    $tier_block->set('field_partners_items', $lb_partners_items_block_ids);
    $tier_block->save();

    // Save new Partner Tier block inside parent Partners block.
    if ($lb_partners_block->bundle() === 'lb_partners') {
      $lb_partners_block->set('field_partners', $tier_block->id())->save();
    }
    $sandbox['progress']++;
  }

  $sandbox['#finished'] = empty($sandbox['total']) ? 1 : $sandbox['progress'] / $sandbox['total'];
}

/**
 * Add a Partner Link field.
 */
function lb_partners_blocks_update_91003() {
  $path = \Drupal::service('extension.list.module')->getPath('lb_partners_blocks') . '/config/optional';
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'field.storage.block_content.field_cta',
    'field.field.block_content.lb_partner_item.field_cta',
    'core.entity_form_display.block_content.lb_partner_item.default',
  ]);
}
