<?php

/**
 * @file
 * Primary module hooks for LB Partners Blocks module.
 *
 */

use Drupal\Component\Utility\UrlHelper;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function lb_partners_blocks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lb_partners_blocks module.
    case 'help.page.lb_partners_blocks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Helper module for the custom "Partners Block" type.') . '</p>';
    return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function lb_partners_blocks_theme($existing, $type, $theme, $path) {
  return [
    'block__lb_partners' => [
      'base hook' => 'block',
      'template' => 'block--lb-partners',
    ]
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function lb_partners_blocks_preprocess_block__lb_partners(&$variables) {
  $variables['block_content'] = $variables['elements']['content']['#block_content'];
  $tires = $variables['block_content']->field_partners->referencedEntities();
  $variables['partners'] = $tires ? _lb_partners_blocks_get_partners($tires): [];
}

/**
 * Get partners items grouped by tier. A tier label can be empty.
 *
 * @param \Drupal\Core\Entity\EntityInterface[] $tiers
 *   An array of blocks objects.
 *
 * @return array
 *   Returns an array of grouped by tier items.
 */
function _lb_partners_blocks_get_partners(array $tiers): array {
  $grouped_partners = [];
  foreach ($tiers as $tier) {
    $tier_id = $tier->id();
    $grouped_partners[$tier_id] = [
      'tier' => $tier?->field_title?->value ?? '',
    ];
    $partners = [];
    $partner_tiers = $tier?->field_partners_items?->referencedEntities();
    if (!$partner_tiers) {
      return [];
    }
    foreach ($partner_tiers as $partner_item) {
      $partner['name'] = $partner_item?->field_partner_name?->value;

      if (!$partner_item->get('field_partner_logo')->isEmpty()) {
        $partner['logo'] = $partner_item->field_partner_logo->entity?->field_media_image?->entity?->createFileUrl(FALSE);
        $partner['logo_alt'] = $partner_item->field_partner_logo->entity->field_media_image->alt ?? t("Partner's photo");;
      }
      if ($partner_item->hasField('field_cta') && !$partner_item->get('field_cta')->isEmpty()) {
        $partner_uri = $partner_item->get('field_cta')?->first()?->uri;
        $external = UrlHelper::isExternal($partner_uri) && UrlHelper::isValid($partner_uri);
        $partner['link'] = $external
          ? $partner_uri
          : Url::fromUri($partner_uri)->toString();
      }
      $partners[] = $partner;
    }
    $grouped_partners[$tier_id]['partners'] = $partners;
  }
  return $grouped_partners;
}

/**
 * Implements hook_ENTITY_TYPE_presave() for block entities.
 */
function lb_partners_blocks_block_content_presave(EntityInterface $block) {
  if ($block->bundle() === 'lb_partner_item') {
    $label = $block->field_partner_name->value;
    $block->setInfo($label);
  }
}
