<?php

/**
 * @file
 * Primary module hooks for LB Statistics module.
 *
 * @DCG
 * This file is no longer required in Drupal 8.
 * @see https://www.drupal.org/node/2217931
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function lb_statistics_theme($existing, $type, $theme, $path) {
  return [
    'block__lb_statistics' => [
      'base hook' => 'block',
      'template' => 'block--lb-statistics',
    ]
  ];
}

/**
 * Implements hook_preprocess_block().
 */
function lb_statistics_preprocess_block__lb_statistics(&$variables) {
  $variables['block_content'] = $variables['elements']['content']['#block_content'];
  $blocks = $variables['block_content']->field_block_item->referencedEntities();
  if ($blocks) {
    foreach ($blocks as $item) {
      $element = [
        'number' => 0,
        'description' => $item->field_title->value
      ];

      $number = trim($item->field_subtitle->value);
      if (preg_match('/^(?P<prefix>[\D]*)(?P<number>[\d\.,]*)(?P<suffix>[^\d]*)$/', $number, $matches)) {
        $element['prefix'] = $matches['prefix'] ?? '';
        $element['number'] = str_replace(',', '', $matches['number']) ?? 0;
        $element['suffix'] = $matches['suffix'] ?? '';
      }

      $variables['items'][] = $element;
    }
  }

}
/**
 * Implements hook_ENTITY_TYPE_presave() for block entities.
 */
function lb_statistics_block_content_presave(EntityInterface $block) {
  if ($block->bundle() === 'statistics_item') {
    $block->setInfo($block->get('field_subtitle')->value);
  }
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function lb_statistics_inline_entity_form_entity_form_alter(array &$entity_form, FormStateInterface $form_state) {
  $entity = $entity_form['#entity'];
  if ($entity->bundle() === 'statistics_item' && !empty($form_state->getUserInput()['settings']['block_form']['field_block_item']['form'])) {
    $form = $form_state->getUserInput()['settings']['block_form']['field_block_item']['form'];
    if (isset($form['inline_entity_form'])) {
      $resultForm = reset($form['inline_entity_form']['entities'])['form'];
    }
    else {
      $resultForm = reset($form);
    }
    $entity->setInfo($resultForm['field_title']['0']['value']);
  }
}
