<?php

use Drupal\Core\Url;


/**
 * Implements hook_theme().
 */
function ws_promotion_hero_theme($existing, $type, $theme, $path) {
  return [
    'node__promo__lb_hero_standard' => [
      'base hook' => 'node',
      'template' => 'node--promo--lb-hero-standard',
    ],
    'node__promo__lb_hero_chevron' => [
      'base hook' => 'node',
      'template' => 'node--promo--lb-hero-chevron',
    ],
    'node__promo__lb_hero_frame' => [
      'base hook' => 'node',
      'template' => 'node--promo--lb-hero-frame',
    ],
    'node__promo__lb_hero_overlay' => [
      'base hook' => 'node',
      'template' => 'node--promo--lb-hero-overlay',
    ],
    'node__promo__lb_hero_overlay_canada_black' => [
      'base hook' => 'node',
      'template' => 'node--promo--lb-hero-overlay-canada-black',
    ],
    'node__promo__lb_hero_overlay_canada_red' => [
      'base hook' => 'node',
      'template' => 'node--promo--lb-hero-overlay-canada-red',
    ],
    'node__promo__lb_hero_overlay_canada_white' => [
      'base hook' => 'node',
      'template' => 'node--promo--lb-hero-overlay-canada-white',
    ],
    'node__promo__lb_hero_small_canada' => [
      'base hook' => 'node',
      'template' => 'node--promo--lb-hero-small-canada',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ws_promotion_hero_preprocess_block__lb_hero(&$variables) {
  $configuration = $variables['elements']['#configuration'];
  if (empty($configuration['promotion_include'])) {
    return;
  }
  $block = $variables['block_content'];
  $variables['#attached']['library'][] = 'ws_promotion_hero/insert_promotion';
  $paramsRoute = ['widget' => $configuration['block_variation'] ?? $variables['derivative_plugin_id']];
  if (!empty($configuration['promotion_category'])) {
    $paramsRoute['category'] = $configuration['promotion_category'];
  }
  $variables['#attached']['drupalSettings']['ws_promotion_hero'][$block->getRevisionId()] = [
    'url' => Url::fromRoute('ws_promotion.get_promo', $paramsRoute, ['absolute' => TRUE])->toString(),
  ];
}

/**
 * Implements hook_promotion_block_list_alter().
 * Add the name of the block to the list for the promotion alter form.
 */
function ws_promotion_hero_promotion_block_list_alter(array &$listOfBlocks) {
  $listOfBlocks[] = 'lb_hero';
}

/**
 * Implements hook_promotion_preview_list_alter().
 * Add the name of the preview template to the list for the promotion preview.
 */
function ws_promotion_hero_promotion_preview_list_alter(array &$listOfPreview) {
  $listOfPreview['lb_hero_standard'] = t('Banner (standard)');
  $listOfPreview['lb_hero_chevron'] = t('Banner (chevron)');
  $listOfPreview['lb_hero_overlay'] = t('Banner (overlay)');
  $listOfPreview['lb_hero_frame'] = t('Banner (frame)');
  $listOfPreview['lb_hero_small'] = t('Banner (small)');
}
