<?php

/**
 * Change label and description of field "field_modal_dismissible"
 */
function lb_modal_update_9001(&$sandbox) {
  $path = \Drupal::service('extension.list.module')->getPath('lb_modal') . '/config/optional';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'field.field.block_content.lb_modal.field_modal_dismissible',
  ]);
}
