<?php

/**
 * @file
 * Primary module hooks for YMCA Website Services - Small Y Search module.
 */

use Drupal\views\ViewExecutable;
use Drupal\views\Views;

/**
 * Implements hook_theme().
 */
function small_y_search_theme($existing, $type, $theme, $path) {
  return [
    'node__lb_event__search_result' => [
      'base hook' => 'node',
    ],
    'node__article_lb__search_result' => [
      'base hook' => 'node',
    ],
    'node__landing_page_lb__search_result' => [
      'base hook' => 'node',
    ],
    'node__branch__search_result' => [
      'base hook' => 'node',
    ],
    'block__lb_search_results' => [
      'base hook' => 'block',
      'template' => 'block--lb-search-results'
    ],
    'views_exposed_form__small_y_content_search__smally_search_results' => [
      'render element' => 'form',
    ],
  ];
}

/**
 * Implements hook_views_pre_render().
 */
function small_y_search_views_pre_render(ViewExecutable $view): void {
  if ($view->storage->id() === 'small_y_content_search') {
    $view->element['#attached']['library'][] = 'small_y_search/search';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function small_y_search_preprocess_block__lb_search_results(&$variables) {
  /** @var  \Drupal\views\ViewExecutable $view */
  $view = Views::getView('small_y_content_search');
  if ($view) {
    $view->setItemsPerPage(10);
    $view->setDisplay('smally_search_results');
    $view->setArguments([]);
    $view->preExecute();
    $view->execute();
  }
  $variables['search_results'] = $view->render('smally_search_results');
}
