<?php

/**
 * @file
 *  Contains install and update functions for Y Layout Builder - Hero module.
 */

/**
 * Implements hook_update_N().
 */
function lb_hero_update_9001(&$sandbox) {
 $path = \Drupal::service('extension.list.module')->getPath('lb_carousel') . '/config/optional';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
   'image.style.hero_banner_desktop',
   'image.style.hero_banner_mobile',
  ]);
}

/**
 * Implements hook_update_N().
 * Rename label block
 */
function lb_hero_update_9002(&$sandbox) {
 $path = \Drupal::service('extension.list.module')->getPath('lb_hero') . '/config/optional';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'block_content.type.lb_hero',
  ]);
}

/**
 * Add a heading level field to the Banner block.
 */
function lb_hero_update_10001(&$sandbox) {
  $path = \Drupal::service('extension.list.module')->getPath('lb_hero') . '/config/optional';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'field.storage.block_content.field_heading_level',
    'field.field.block_content.lb_hero.field_heading_level',
    'core.entity_form_display.block_content.lb_hero.default',
    'core.entity_view_display.block_content.lb_hero.default',
    'language.content_settings.block_content.lb_hero',
  ]);
}

/**
 * Revert unintentional media widget change from lb_hero_update_10001.
 */
function lb_hero_update_10002(&$sandbox) {
  $path = \Drupal::service('extension.list.module')->getPath('lb_hero') . '/config/optional';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'core.entity_form_display.block_content.lb_hero.default'
  ]);
}

/**
 * Imports the hero_banner_retina_2x image style from optional config.
 */
function lb_hero_update_10003(&$sandbox) {
  $path = \Drupal::service('extension.list.module')->getPath('lb_hero') . '/config/optional';
   /** @var \Drupal\config_import\ConfigImporterService $config_importer */
   $config_importer = \Drupal::service('config_import.importer');
   $config_importer->setDirectory($path);
   $config_importer->importConfigs([
    'image.style.hero_banner_retina_2x',
   ]);
 }


/**
 * Allow attributes on links (target, id, class).
 */
function lb_hero_update_10004() {
  $path = \Drupal::service('extension.list.module')
      ->getPath('lb_hero') . '/config/optional';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'core.entity_form_display.block_content.lb_hero.default',
  ]);
}
