<?php

/**
 * @file
 * Installation and update implementations.
 */

use Drupal\block_content\Entity\BlockContent;
use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;
use Drupal\field\FieldStorageConfigInterface;
use Drupal\layout_builder\Section;
use Drupal\layout_builder\SectionComponent;

/**
 * Implements hook_install().
 */
function y_facility_install() {
  // Create required fields.
  _y_facility_create_fields();
  // Update form and view displays for Facility content type.
  _y_facility_update_displays_on_install();
  // Modify Facility content type field groups on the form.
  _y_facility_update_field_groups_on_install();
  // Modify Facility content type. Create new fields
  _y_facility_update_field_and_create();
}

/**
 * Implements hook_install().
 */
function y_facility_uninstall() {
  // Remove field.
  _y_facility_remove_fields();
  // Update form and view displays for Facility content type.
  _y_facility_update_displays_on_unistall();
  // Update and remove Facility content type field groups on the form.
  _y_facility_update_field_groups_on_uninstall();
}

/**
 * Create required fields.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function _y_facility_create_fields() {
  // Create field storage if not exist and config for 'Use Layout Builder' field.
  $field_storage_config = FieldStorageConfig::loadByName('node', 'field_use_layout_builder');
  if (!$field_storage_config instanceof FieldStorageConfigInterface) {
    FieldStorageConfig::create([
      'field_name' => 'field_use_layout_builder',
      'entity_type' => 'node',
      'type' => 'boolean',
      'cardinality' => 1,
    ])->save();
  }

  FieldConfig::create([
    'field_name' => 'field_use_layout_builder',
    'entity_type' => 'node',
    'bundle' => 'facility',
    'label' => 'Use Layout Builder',
    'description' => 'Change display option of the Facility.',
  ])->save();

}

/**
 * Update required field groups on install.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function _y_facility_update_field_groups_on_install() {
  // Deprecate existing groups.
  $deprecated_groups = [
    31 => 'group_content_area',
    32 => 'group_bottom_area',
  ];

  foreach ($deprecated_groups as $weight => $deprecated_group) {
    $group = field_group_load_field_group($deprecated_group, 'node', 'facility', 'form', 'default');
    if ($group) {
      $group->weight = $weight;
      $group->label = $group->label . ' (deprecated, not displayed in Layout Builder)';
    }
    field_group_group_save($group);
  }
}

/**
 * Update required field groups on uninstall.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function _y_facility_update_field_groups_on_uninstall() {
  // Deprecate existing groups.
  $deprecated_groups = [
    19 => 'group_content_area',
    20 => 'group_bottom_area',
  ];

  foreach ($deprecated_groups as $weight => $deprecated_group) {
    $group = field_group_load_field_group($deprecated_group, 'node', 'facility', 'form', 'default');
    if ($group) {
      $group->weight = $weight;
      $group->label = str_replace(' (deprecated, not displayed in Layout Builder)', '', $group->label);
    }
    field_group_group_save($group);
  }
}

/**
 * Update Facility content type display modes on enabling the module.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function _y_facility_update_displays_on_install() {
  /** @var \Drupal\Core\Entity\EntityDisplayRepositoryInterface $entity_display_repository */
  $entity_display_repository = \Drupal::service('entity_display.repository');

  // Update Facility content type form display.
  /** @var \Drupal\Core\Entity\Display\EntityFormDisplayInterface $form_display */
  $form_display = $entity_display_repository->getFormDisplay('node', 'facility');
  $form_display->setComponent('field_use_layout_builder', [
    'type' => 'boolean_checkbox',
    'settings' => [
      'display_label' => TRUE,
    ],
    'weight' => 51,
  ]);

  $form_display->save();

  // Update Facility content type view displays.
  $view_modes = $entity_display_repository
    ->getViewModeOptionsByBundle('node', 'facility');
  foreach (array_keys($view_modes) as $view_mode) {
    /** @var \Drupal\Core\Entity\Display\EntityViewDisplayInterface $view_display */
    $view_display = $entity_display_repository->getViewDisplay('node', 'facility', $view_mode);
    $fields = [
      'field_use_layout_builder',
    ];
    foreach ($fields as $field) {
      $view_display->removeComponent($field);
    }
    if ($view_mode == 'full') {
      $sections = _y_facility_create_sections_layout_builder();
      $view_display
        ->setThirdPartySetting('layout_builder', 'enabled', TRUE)
        ->setThirdPartySetting('layout_builder', 'allow_custom', TRUE)
        ->setThirdPartySetting('layout_builder', 'sections', $sections)
        ->setThirdPartySetting('y_lb', 'styles', [
          'colorway' => 'ws_colorway_blue',
          'border_radius' => 'ws_border_radius_none',
          'border_style_global' => 'ws_border_style_global_drop_shadow',
          'text_alignment_global' => 'ws_text_alignment_global_left',
          'button_position_global' => 'ws_button_position_global_inside',
          'button_fill_global' => 'ws_button_fill_global_filled',
        ])
        ->setThirdPartySetting('layout_builder_restrictions', 'entity_view_mode_restriction', [
          'allowed_layouts' => [
            'bootstrap_layout_builder:blb_col_1',
            'bootstrap_layout_builder:blb_col_2',
            'bootstrap_layout_builder:blb_col_3',
            'bootstrap_layout_builder:blb_col_4',
            'ws_header',
            'ws_footer',
          ],
        ]);
      $view_display->removeComponent('layout_builder__layout');
    }
    $view_display->save();
  }
  // Update restrictions inline blocks
  y_facility_update_9001();
}

/**
 * Create sections and blocks for layout builder
 */
function _y_facility_create_sections_layout_builder() {
  $uuid_service = \Drupal::service('uuid');
  $sections = [];

  // Section WS Header
  $section = new Section('ws_header', [
    'container' => 'container',
    'label' => 'Header',
  ]);

  $component = new SectionComponent($uuid_service->generate(), 'header_top_left', [
    'id' => 'ws_site_name',
    'label' => 'Website Name Block',
    'label_display' => '0',
    'provider' => 'y_lb',
  ]);
  $section->appendComponent($component);

  $component = new SectionComponent($uuid_service->generate(), 'header_top_right', [
    'id' => 'openy_gtranslate_block',
    'label' => 'Open Y Google Translate',
    'label_display' => '0',
    'provider' => 'openy_gtranslate',
  ]);
  $section->appendComponent($component);

  $component = new SectionComponent($uuid_service->generate(), 'header_top_right', [
    'id' => 'system_menu_block:utility',
    'label' => 'Utility Menu',
    'label_display' => '0',
    'provider' => 'system',
    'level' => '1',
    'depth' => '1',
    'expand_all_items' => FALSE,
  ]);
  $section->appendComponent($component);

  $component = new SectionComponent($uuid_service->generate(), 'header_bottom_left', [
    'id' => 'ws_site_logo',
    'label' => 'Site Logo Block',
    'label_display' => '0',
    'provider' => 'y_lb',
    'logo_type' => 'colorway',
  ]);
  $section->appendComponent($component);

  $component = new SectionComponent($uuid_service->generate(), 'header_bottom_middle', [
    'id' => 'system_menu_block:main',
    'label' => 'Main navigation',
    'label_display' => '0',
    'provider' => 'system',
    'level' => '1',
    'depth' => '0',
    'expand_all_items' => FALSE,
  ]);
  $section->appendComponent($component);

  $component = new SectionComponent($uuid_service->generate(), 'header_bottom_middle', [
    'id' => 'ws_search_bar',
    'label' => 'Search Bar Block',
    'label_display' => '0',
    'provider' => 'y_lb',
  ]);
  $section->appendComponent($component);
  $sections[] = $section;

  $component = new SectionComponent($uuid_service->generate(), 'header_bottom_right', [
    'id' => 'system_menu_block:account',
    'label' => 'User account menu',
    'label_display' => '0',
    'provider' => 'system',
    'level' => '1',
    'depth' => '0',
    'expand_all_items' => FALSE,
  ]);
  $section->appendComponent($component);

  // Section Facility Header
  $section = new Section('bootstrap_layout_builder:blb_col_1', [
    'container' => 'container',
    'label' => 'Facility header',
    'container_wrapper' => [
      'bootstrap_styles' => [
        'background' => ['background_type' => 'color'],
        'background_color' => ['class' => 'ylb-bg-semi-light-grey'],
        'text_color' => ['class' => 'ylb-text-white'],
      ],
    ],
    'container_wrapper_classes' => 'location-header',
  ]);
  $component = new SectionComponent($uuid_service->generate(), 'blb_region_col_1', [
    'id' => 'lb_branch_hours',
    'label' => 'Facility Hours',
    'label_display' => '0',
    'provider' => 'lb_branch_hours_blocks',
    'context_mapping' => ['node' => 'layout_builder.entity'],
  ]);
  $section->appendComponent($component);
  $sections[] = $section;

  // Section Social links
  $sections[] = new Section('bootstrap_layout_builder:blb_col_1', [
    'container' => 'container',
    'label' => 'Social links',
    'container_wrapper_classes' => 'mt-3',
  ]);

  // Section Body
  $sections[] = new Section('bootstrap_layout_builder:blb_col_1', [
    'container' => 'container',
    'label' => 'Body',
  ]);

  // Section Amenities
  $section = new Section('bootstrap_layout_builder:blb_col_1', [
    'container' => 'container',
    'label' => 'Amenities',
    'container_wrapper' => [
      'bootstrap_styles' => [
        'background' => ['background_type' => 'color'],
        'background_color' => ['class' => 'ylb-bg-semi-light-grey'],
        'text_color' => ['class' => 'ylb-text-white'],
      ],
    ],
  ]);

  $block_content = BlockContent::create([
    'type' => 'lb_branch_amenities_blocks',
    'info' => 'Facility Amenities',
    'reusable' => '0',
  ]);
  $block_content->save();

  $component = new SectionComponent($uuid_service->generate(), 'blb_region_col_1', [
    'id' => 'inline_block:lb_branch_amenities_blocks',
    'label' => 'Facility Amenities Block',
    'label_display' => '0',
    'provider' => 'layout_builder',
    'view_mode' => 'full',
    'block_revision_id' => $block_content->getRevisionId(),
  ]);
  $section->appendComponent($component);
  $sections[] = $section;

  // Section WS Footer
  $section = new Section('ws_footer', [
    'container' => 'container',
    'label' => 'Footer',
  ]);

  $component = new SectionComponent($uuid_service->generate(), 'footer_top_left', [
    'id' => 'ws_site_logo',
    'label' => 'Site Logo Block',
    'label_display' => '0',
    'provider' => 'y_lb',
    'logo_type' => 'white',
  ]);
  $section->appendComponent($component);

  $component = new SectionComponent($uuid_service->generate(), 'footer_top_right', [
    'id' => 'ws_social',
    'label' => 'Stay Connected',
    'label_display' => 'visible',
    'provider' => 'y_lb',
  ]);
  $section->appendComponent($component);

  $component = new SectionComponent($uuid_service->generate(), 'footer_bottom_right', [
    'id' => 'system_menu_block:footer',
    'label' => 'Footer navigation',
    'label_display' => '0',
    'provider' => 'system',
    'level' => '1',
    'depth' => '0',
    'expand_all_items' => FALSE,
  ]);
  $section->appendComponent($component);

  $component = new SectionComponent($uuid_service->generate(), 'footer_bottom_left', [
    'id' => 'ws_copyright',
    'label' => 'Copyright Block',
    'label_display' => '0',
    'provider' => 'y_lb',
  ]);
  $section->appendComponent($component);

  $component = new SectionComponent($uuid_service->generate(), 'footer_top_middle', [
    'id' => 'system_menu_block:footer-menu-left',
    'label' => 'Left',
    'label_display' => 'visible',
    'provider' => 'system',
  ]);
  $section->appendComponent($component);

  $component = new SectionComponent($uuid_service->generate(), 'footer_top_middle', [
    'id' => 'system_menu_block:footer-menu-center',
    'label' => 'Center',
    'label_display' => 'visible',
    'provider' => 'system',
    'level' => '1',
    'depth' => '0',
    'expand_all_items' => FALSE,
  ]);
  $section->appendComponent($component);

  $component = new SectionComponent($uuid_service->generate(), 'footer_top_middle', [
    'id' => 'system_menu_block:footer-menu-right',
    'label' => 'Right',
    'label_display' => 'visible',
    'provider' => 'system',
    'level' => '1',
    'depth' => '0',
    'expand_all_items' => FALSE,
  ]);
  $section->appendComponent($component);
  $sections[] = $section;

  return $sections;
}

/**
 * Remove required fields.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function _y_facility_remove_fields() {
  $field = 'field_use_layout_builder';
  $field_config = FieldConfig::loadByName('node', 'facility', $field);
  if ($field_config instanceof FieldConfig) {
    $field_config->delete();
  }
  // Deleting field storage.
  // Don't remove the fields if it can be used in other module.
  if (!Drupal::service('module_handler')->moduleExists('y_branch')) {
    $field_config_storage = FieldStorageConfig::loadByName('node', $field);
    if ($field_config_storage instanceof FieldStorageConfigInterface) {
      $field_config_storage->delete();
    }
  }
}

/**
 * Update Facility content type display modes on disabling the module.
 *
 * @throws \Drupal\Core\Entity\EntityStorageException
 */
function _y_facility_update_displays_on_unistall() {
  /** @var \Drupal\Core\Entity\EntityDisplayRepositoryInterface $entity_display_repository */
  $entity_display_repository = \Drupal::service('entity_display.repository');
  // Update Facility content type view displays.
  $view_modes = $entity_display_repository
    ->getViewModeOptionsByBundle('node', 'facility');

  foreach (array_keys($view_modes) as $view_mode) {
    /** @var \Drupal\Core\Entity\Display\EntityViewDisplayInterface $view_display */
    $view_display = $entity_display_repository->getViewDisplay('node', 'facility', $view_mode);
    if ($view_mode == 'full') {
      $view_display
        ->setThirdPartySetting('layout_builder', 'enabled', FALSE);
    }
    $view_display->save();
  }
}

/**
 * Set not required some fields.
 * Create new fields: field_branch_hours and field_branch_holiday_hours
 */
function _y_facility_update_field_and_create() {
  $fields = [
    'field_location_address',
    'field_location_coordinates',
    'field_location_phone'
  ];

  foreach ($fields as $field) {
    $field_config = FieldConfig::loadByName('node', 'facility', $field);
    if ($field_config) {
      $field_config->setRequired(FALSE);
      $field_config->save();
    }
  }
}

/**
 * Add restrictions inline blocks for display full.
 */
function y_facility_update_9001(&$sandbox = NULL) {
  $entity_display_repository = \Drupal::service('entity_display.repository');

  // Update Facility content type view displays.
  $view_modes = $entity_display_repository
    ->getViewModeOptionsByBundle('node', 'facility');
  foreach (array_keys($view_modes) as $view_mode) {
    /** @var \Drupal\Core\Entity\Display\EntityViewDisplayInterface $view_display */
    $view_display = $entity_display_repository->getViewDisplay('node', 'facility', $view_mode);
    if ($view_mode == 'full') {
      $restrictions = $view_display
        ->getThirdPartySetting('layout_builder_restrictions', 'entity_view_mode_restriction');

      $denylistedBlocks = $restrictions['denylisted_blocks'] ?? [];
      $denylistedBlocks['Inline blocks'] = array_unique(array_merge($denylistedBlocks['Inline blocks'] ?? [], [
        'inline_block:branch_amenities',
        'inline_block:testimonial_item',
      ]));
      $restrictions['denylisted_blocks'] = $denylistedBlocks;
      $view_display
        ->setThirdPartySetting('layout_builder_restrictions', 'entity_view_mode_restriction', $restrictions);

      $view_display->save();
    }
  }
}

/**
 * Change the default logo in WS Footer to the white one in LB view.
 */
function y_facility_update_9002(&$sandbox = NULL) {
  $entity_display_repository = \Drupal::service('entity_display.repository');

  // Update Branch content type view displays.
  $view_modes = $entity_display_repository
    ->getViewModeOptionsByBundle('node', 'branch');
  foreach (array_keys($view_modes) as $view_mode) {
    /** @var \Drupal\Core\Entity\Display\EntityViewDisplayInterface $view_display */
    $view_display = $entity_display_repository->getViewDisplay('node', 'facility', $view_mode);
    if ($view_mode == 'full') {
      $sections = _y_facility_create_sections_layout_builder();
      $view_display
        ->setThirdPartySetting('layout_builder', 'sections', $sections);
    }
    $view_display->save();
  }
}

/**
 * Update Contact/Hours behavior.
 */
function y_facility_update_9003(&$sandbox = NULL) {
  _y_facility_update_field_and_create();
}

/**
 * Update Contact/Hours behavior.
 */
function y_facility_update_9004(&$sandbox = NULL) {
  _y_facility_update_field_and_create();
}

/**
 * Update default Y styles options if they're empty.
 */
function y_facility_update_9005(&$sandbox = NULL) {
  $entity_display_repository = \Drupal::service('entity_display.repository');

  // Update Facility content type style defaults.
  $view_modes = $entity_display_repository
    ->getViewModeOptionsByBundle('node', 'facility');
  foreach (array_keys($view_modes) as $view_mode) {
    /** @var \Drupal\Core\Entity\Display\EntityViewDisplayInterface $view_display */
    $view_display = $entity_display_repository->getViewDisplay('node', 'facility', $view_mode);
    if ($view_mode == 'full') {
      $styles = $view_display->getThirdPartySetting('y_lb', 'styles');
      $default_styles = [
        'colorway' => 'ws_colorway_blue',
        'border_radius' => 'ws_border_radius_none',
        'border_style_global' => 'ws_border_style_global_drop_shadow',
        'text_alignment_global' => 'ws_text_alignment_global_left',
        'button_position_global' => 'ws_button_position_global_inside',
        'button_fill_global' => 'ws_button_fill_global_filled',
      ];

      // Merge the existing styles into the default. Any exising settings will
      // override the defaults. NULL values will be filtered out.
      $styles = array_merge($default_styles, array_filter($styles));

      $view_display
        ->setThirdPartySetting('y_lb', 'styles', $styles);
    }
    $view_display->save();
  }
}

/**
 * Add Utility Menu to Facility template.
 */
function y_facility_update_9006(&$sandbox = NULL) {
  $entity_display_repository = \Drupal::service('entity_display.repository');

  // Update Facility template with Utility Menu.
  $view_modes = $entity_display_repository
    ->getViewModeOptionsByBundle('node', 'facility');
  foreach (array_keys($view_modes) as $view_mode) {
    /** @var \Drupal\Core\Entity\Display\EntityViewDisplayInterface $view_display */
    $view_display = $entity_display_repository->getViewDisplay('node', 'facility', $view_mode);
    if ($view_mode == 'full') {

      $sections = $view_display->getThirdPartySetting('layout_builder', 'sections');
      foreach ($sections as $index => $section) {
        if ($section->getLayoutId() == 'ws_header') {
          // Instantiate new Utility Menu section.
          $uuid_service = \Drupal::service('uuid');
          $component = new SectionComponent($uuid_service->generate(), 'header_top_right', [
            'id' => 'system_menu_block:utility',
            'label' => 'Utility Menu',
            'label_display' => '0',
            'provider' => 'system',
            'level' => '1',
            'depth' => '1',
            'expand_all_items' => FALSE,
          ]);
          // Add the menu to the section, add the section back to sections, and save.
          $section->appendComponent($component);
          $sections[$index] = $section;
          $view_display->setThirdPartySetting('layout_builder', 'sections', $sections);

          $view_display->save();
        }
      }
    }
  }
}
