<?php
/**
 * @file
 * Y-LB Blocks Ping-Pong submodule.
 */

/**
 * Implements hook_theme().
 */
function lb_ping_pong_theme($existing, $type, $theme, $path) {
  return [
    'block__lb_ping_pong' => [
      'base hook' => 'block',
      'template' => 'block--lb-ping-pong',
    ],
    'block__lb_ping_pong__equal_column' => [
      'base hook' => 'block',
      'template' => 'block--lb-ping-pong--equal-column',
    ],
    'block__lb_ping_pong__first_column' => [
      'base hook' => 'block',
      'template' => 'block--lb-ping-pong--first-column',
    ],
    'block__lb_ping_pong__second_column' => [
      'base hook' => 'block',
      'template' => 'block--lb-ping-pong--second-column',
    ]
  ];
}

/**
 * Implements template_preprocess_HOOK().
 */
function lb_ping_pong_preprocess_block__lb_ping_pong(&$variables) {
  $variables['block_content'] = $variables['elements']['content']['#block_content'];
  $variables['image_position'] = $variables['block_content']->field_item_image_position->value ?? 'left';
  if ($variables['block_content']->field_item_image) {
    $variables['image_uri'] = $variables['block_content']->field_item_image->entity->field_media_image->entity->uri->value ?? null;
    $variables['image_alt'] = $variables['block_content']->field_item_image->entity->field_media_image->alt ?? null;
  }
}
