<?php

/**
 * @file
 * Primary module hooks for Y Layout Builder - Carousel module.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Routing\RouteMatchInterface;

 /**
 * Implements hook_help().
 */
function lb_carousel_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the lb_carousel module.
    case 'help.page.lb_carousel':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Carousel for Layout Builder') . '</p>';
      return $output;
  }
}

/**
 * Implements hook_theme().
 */
function lb_carousel_theme($existing, $type, $theme, $path) {
  return [
    'block__lb_carousel' => [
      'base hook' => 'block',
      'template' => 'block--lb-carousel',
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lb_carousel_preprocess_block__lb_carousel(&$variables) {
  $variables['block_content'] = $variables['elements']['content']['#block_content'];
  $variables['items'] = $variables['block_content']->field_block_item->referencedEntities();
  $variables['show_controls'] = count($variables['items']) > 1;
}


/**
 * Implements hook_ENTITY_TYPE_presave() for block entities.
 */
function lb_carousel_block_content_presave(EntityInterface $block) {
  if ($block->bundle() === 'carousel_item') {
    $block->setInfo($block->get('field_title')->value ?? 'Carousel item');
  }
}

/**
 * Implements hook_inline_entity_form_entity_form_alter().
 */
function lb_carousel_inline_entity_form_entity_form_alter(array &$entity_form, FormStateInterface $form_state) {
  $entity = $entity_form['#entity'];
  if ($entity->bundle() === 'carousel_item' && !empty($form_state->getUserInput()['settings']['block_form']['field_block_item']['form'])) {
    $form = $form_state->getUserInput()['settings']['block_form']['field_block_item']['form'];
    if (isset($form['inline_entity_form'])) {
      $resultForm = reset($form['inline_entity_form']['entities'])['form'];
    }
    else {
      $resultForm = reset($form);
    }
    $entity->setInfo($resultForm['field_title']['0']['value'] ?: 'Carousel item');
  }
}

