<?php

/**
 * @file
 *  Contains install and update functions for Y Layout Builder - Carousel module.
 */

use Drupal\field\Entity\FieldConfig;
use Drupal\field\Entity\FieldStorageConfig;

/**
 * Issue #3352920 Add a focal point effect and a convert to webp effect to the image styles.
 */
function lb_carousel_update_9001(&$sandbox) {
  $path = \Drupal::service('extension.list.module')->getPath('lb_carousel') . '/config/optional';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'image.style.hero_banner_desktop',
    'image.style.hero_banner_mobile',
  ]);
}

/**
 * Import config to create 'carousel_item' sub block for 'lb_carousel' block.
 */
function lb_carousel_update_9002() {
  $path = \Drupal::service('extension.list.module')->getPath('lb_carousel') . '/config/optional';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'block_content.type.carousel_item',
    'core.entity_form_display.block_content.carousel_item.default',
    'core.entity_view_display.block_content.carousel_item.default',
    'field.storage.block_content.field_block_item',
    'field.storage.block_content.field_cta',
    'field.storage.block_content.field_description',
    'field.storage.block_content.field_media',
    'field.storage.block_content.field_title',
    'field.field.block_content.carousel_item.field_cta',
    'field.field.block_content.carousel_item.field_description',
    'field.field.block_content.carousel_item.field_media',
    'field.field.block_content.carousel_item.field_title',
    'field.field.block_content.lb_carousel.field_block_item',
    'language.content_settings.block_content.carousel_item',
  ]);
}

/**
 * Migrate content from 'lb_carousel_item' paragraph to 'carousel_item' block.
 */
function lb_carousel_update_9003(&$sandbox) {
  /** @var \Drupal\Core\Entity\EntityTypeManager $entityTypeManager */
  $entityTypeManager = \Drupal::entityTypeManager();
  $storageParagraph = $entityTypeManager->getStorage('paragraph');
  $storageBlock = $entityTypeManager->getStorage('block_content');
  if (!isset($sandbox['progress'])) {
    $sandbox['progress'] = 0;
    $sandbox['data'] = [
      'paragraphs' => $storageParagraph->loadByProperties(['type' => 'lb_carousel_item']),
      'blocks' => []
    ];
    // Group paragraphs by parent id.
    foreach ($sandbox['data']['paragraphs'] as $id => $paragraph) {
      $sandbox['data']['blocks'][$paragraph->get('parent_id')->value][] = $id;
    }
    $sandbox['total'] = count($sandbox['data']['blocks']);
  }

  $blocks = array_slice($sandbox['data']['blocks'], $sandbox['progress'], 5, true);

  foreach ($blocks as $parentId => $paragraphIds) {
    $newBlockIds = [];

    foreach ($paragraphIds as $paragraphId) {
      $paragraph = $sandbox['data']['paragraphs'][$paragraphId];
      // Create new 'carousel_item' sub block with content from paragraph
      $block = $storageBlock->create([
        'type' => 'carousel_item',
        'field_description' => $paragraph->get('field_carousel_description')->getValue(),
        'field_title' => $paragraph->get('field_title')->getValue(),
        'field_media' => $paragraph->get('field_carousel_image')->getValue(),
        'field_cta' => $paragraph->get('field_carousel_cta')->getValue(),
      ]);

      $block->save();
      $newBlockIds[] = $block->id();
      $paragraph->delete();
    }

    // Load parent block and set new sub block.
    /** @var \Drupal\block_content\Entity\BlockContent $parentBlock */
    if (($parentBlock = $storageBlock->load($parentId)) && $parentBlock->bundle() === 'lb_carousel') {
      $parentBlock->set('field_block_item', $newBlockIds)->save();
    }
    $sandbox['progress']++;
  }

  $sandbox['#finished'] = empty($sandbox['total']) ? 1 : $sandbox['progress'] / $sandbox['total'];
}

/**
 * Remove 'lb_carousel_item' paragraph config
 */
function lb_carousel_update_9004() {
  $path = \Drupal::service('extension.list.module')->getPath('lb_carousel') . '/config/optional';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');

  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'core.entity_form_display.block_content.lb_carousel.default',
    'core.entity_view_display.block_content.lb_carousel.default',
  ]);

  $configsToDelete = [
    'paragraphs.paragraphs_type.lb_carousel_item',
    'core.entity_form_display.paragraph.lb_carousel_item.default',
    'core.entity_view_display.paragraph.lb_carousel_item.default',
  ];

  $configFactory = \Drupal::configFactory();
  foreach ($configsToDelete as $config) {
    $configFactory->getEditable($config)->delete();
  }

  FieldConfig::loadByName('paragraph', 'lb_carousel_item', 'field_title')?->delete();
  FieldConfig::loadByName('paragraph', 'lb_carousel_item', 'field_carousel_image')?->delete();
  FieldConfig::loadByName('paragraph', 'lb_carousel_item', 'field_carousel_description')?->delete();
  FieldConfig::loadByName('paragraph', 'lb_carousel_item', 'field_carousel_cta')?->delete();
  FieldConfig::loadByName('block_content', 'lb_carousel', 'field_carousel_items')?->delete();

  FieldStorageConfig::loadByName('paragraph', 'field_carousel_image')?->delete();
  FieldStorageConfig::loadByName('paragraph', 'field_carousel_description')?->delete();
  FieldStorageConfig::loadByName('paragraph', 'field_carousel_cta')?->delete();
  FieldStorageConfig::loadByName('block_content', 'field_carousel_items')?->delete();
}

/**
 * Rename label "field_block_item" field
 */
function lb_carousel_update_9005() {
  $path = \Drupal::service('extension.list.module')->getPath('lb_carousel') . '/config/optional';
  /** @var \Drupal\config_import\ConfigImporterService $config_importer */
  $config_importer = \Drupal::service('config_import.importer');
  $config_importer->setDirectory($path);
  $config_importer->importConfigs([
    'field.field.block_content.lb_carousel.field_block_item',
  ]);
}

