<?php

/**
 * @file
 * Primary module hooks for YMCA Website Services - Small Y module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function ws_small_y_theme($existing, $type, $theme, $path) {
  return [
    'ws_header' => [
      'template' => 'small-y-header',
    ],
    'ws_footer' => [
      'template' => 'small-y-footer',
    ],
    'small_y_page_not_found' => [
      'variables' => [
        'sitemap_link' => '',
        'home_link' => '',
      ],
      'template' => 'small-y-page-not-found',
    ],
  ];
}

/**
 * Implements hook_block_alter().
 */
function ws_small_y_block_alter(&$definitions) {
  foreach ($definitions as $id => $definition) {
    if ($id === 'ws_site_logo') {
      $definitions[$id]['class'] = 'Drupal\ws_small_y\Plugin\Block\SmallYSiteLogoBlock';
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ws_small_y_preprocess_ws_footer(&$variables) {
  $variables['#attached']['library'][] = 'ws_small_y/footer';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ws_small_y_preprocess_ws_header(&$variables) {
  $variables['#attached']['library'][] = 'ws_small_y/header';
}

/**
 * Implements hook_preprocess_HOOK().
 */
function ws_small_y_preprocess_ws_camp_header(&$variables) {
  $variables['#attached']['library'][] = 'ws_small_y/header';
}

/**
 * Implements hook_theme_registry_alter().
 */
function ws_small_y_theme_registry_alter(&$theme_registry) {
  $module_handler = \Drupal::service('module_handler');
  $path = $module_handler->getModule('ws_small_y')->getPath();
  $override_components = [
    'block__ws_search_bar',
    'menu__extras',
    'menu__main',
  ];
  foreach ($override_components as $component) {
    if (isset($theme_registry[$component])) {
      $theme_registry[$component]['theme path'] = $path;
      $theme_registry[$component]['path'] = $path . '/templates';
    }
  }
}

/**
 * Implements hook_entity_type_alter().
 */
function ws_small_y_entity_type_alter(array &$entity_types) {
  if (isset($entity_types['menu_link_content'])) {
    $entity_types['menu_link_content']->addConstraint('WsMenuItemOverLimit');
  }
}

/**
 * Implements hook_library_info_alter().
 */
function ws_small_y_library_info_alter(&$libraries, $extension) {
  // To fix for a menu link delete action (see https://www.drupal.org/project/drupal/issues/2755791).
  if ($extension == 'core' && isset($libraries['drupal.ajax'])) {
    $libraries['drupal.ajax']['dependencies'][] = 'core/internal.jquery.form';
  }
}

/**
 * Implements hook_form_alter().
 */
function ws_small_y_form_alter(&$form, FormStateInterface $form_state, $form_id): void {
  $form_ids = [
    'node_branch_form',
    'node_branch_edit_form',
    'node_camp_form',
    'node_camp_edit_form',
    'node_facility_form',
    'node_facility_edit_form',
  ];

  if (in_array($form_id, $form_ids)) {
    _ws_small_y_hide_deprecated_fields($form);
    // Set enable by default and hide.
    $form['field_use_layout_builder']['widget']['value']['#default_value'] = TRUE;
    $form['field_use_layout_builder']['widget']['#access'] = FALSE;
  }
}

/**
 * It hides fields that are deprecated and not needed to show.
 *
 * @param $form
 *   An array of the node's form to handle with.
 *
 */
function _ws_small_y_hide_deprecated_fields(&$form): void {
  $fields_to_hide = [
    'field_header_content',
    'field_content',
    'field_bottom_content',
    'field_sidebar_content',
  ];

  foreach ($fields_to_hide as $field_name) {
    if (isset($form[$field_name])) {
      $form[$field_name]['#access'] = FALSE;
    }
  }
}
