<?php

/**
 * @file
 * Primary module hooks for Layout Builder Related Articles Blocks module.
 */

use Drupal\block_content\BlockContentInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\Views;

/**
 * Implements hook_theme().
 */
function lb_related_articles_blocks_theme() {
  return [
    'block__lb_related_articles' => [
      'base hook' => 'block',
      'template' => 'block--lb-related-articles',
    ],
    'field__block_content__field_related_link' => [
      'base hook' => 'field',
    ],
    'node__article_lb__related_content' => [
      'base hook' => 'node',
    ],
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function lb_related_articles_blocks_preprocess_block__lb_related_articles(&$variables) {
  $variables['block_content'] = $variables['elements']['content']['#block_content'];

  $block = $variables['content']['#block_content'];
  $arguments = [
    'field_location_reference_target_id' => 'all',
    'field_type_value' => 'all',
    'nid' => 'all',
    'field_tags_target_id' => 'all',
  ];
  $widget_type = $block->field_widget_type->value;
  switch ($widget_type) {
    case 'locations':
      $locations = [];
      foreach ($block->get('field_location_reference')->getValue() as $location) {
        $locations[] = $location['target_id'];
      }
      if ($locations) {
        $arguments['field_location_reference_target_id'] = implode('+', $locations);
      }
      break;

    case 'tags':
      $tags = [];
      foreach ($block->get('field_tags')->getValue() as $tag) {
        $tags[] = $tag['target_id'];
      }
      if ($tags) {
        $arguments['field_tags_target_id'] = implode('+', $tags);
      }
      break;

    case 'article_type':
      $arguments['field_type_value'] = $block->field_article_type->value ?: 'all';
      break;

    case 'manual':
      $content_items = [];
      foreach ($block->get('field_content_items')->getValue() as $content_item) {
        $content_items[] = $content_item['target_id'];
      }
      if ($content_items) {
        $arguments['nid'] = implode('+', $content_items);
      }
      break;

    default:
  }

  $currentRouteMatch = Drupal::getContainer()->get('current_route_match');
  if ($currentRouteMatch && $node = $currentRouteMatch->getParameter('node')) {
    $arguments['nid_1'] = $node->id();
  }

  /** @var  \Drupal\views\ViewExecutable $view */
  $view = Views::getView('related_articles');
  if ($view) {
    $view->setItemsPerPage($block->field_items_count_to_display->value);
    $view->setDisplay('related_articles_block');
    $view->setArguments($arguments);
    $view->preExecute();
    $view->execute();
    /** @var  \Drupal\Core\Entity\EntityViewBuilder $view_builder */
  }
  $variables['items'] = $view->render('related_articles_block');
}

/**
 * Implements hook_form_alter().
 */
function lb_related_articles_blocks_form_alter(&$form, FormStateInterface $form_state) {
  // Block configuration form.
  if (in_array($form['#form_id'],
    [
      'layout_builder_add_block',
      'layout_builder_update_block',
    ]
  )) {
    /** @var \Drupal\layout_builder\Form\ConfigureBlockFormBase $form_object */
    $form_object = $form_state->getFormObject();
    $component = $form_object->getCurrentComponent();
    $plugin = $component->getPlugin();
    $block_id = $plugin->getDerivativeId() ?? $plugin->getBaseId();
    // Specify block_id for reusable blocks.
    if ($plugin->getBaseId() == 'block_content') {
      $configuration = $plugin->getConfiguration();
      if (!empty($configuration['type'])) {
        $block_id = $configuration['type'];
      }
      else {
        $block = \Drupal::service('entity.repository')->loadEntityByUuid('block_content', $block_id);
        if ($block instanceof BlockContentInterface) {
          $block_id = $block->bundle();
        }
      }
    }

    if ($block_id == 'lb_related_articles') {
      if (isset($form['block_form'])) {
        $form['block_form']['#process'][] = '_lb_related_articles_blocks_inline_block_process';
      }
      else {
        $form['settings']['block_form']['#process'][] = '_lb_related_articles_blocks_inline_block_process';
      }
    }
  }
}

/**
 * Custom process callback for inline block elements.
 *
 * @param array $element
 *   Element to process.
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *   The form state.
 *
 * @return array
 *   Processed element.
 */
function _lb_related_articles_blocks_inline_block_process(array $element, FormStateInterface $form_state) {
  if (isset($element['field_location_reference'])) {
    $element['field_location_reference']['widget']['#after_build'][] = '_lb_related_articles_blocks_field_location_reference_after_build';
  }
  if (isset($element['field_tags'])) {
    $element['field_tags']['widget']['#after_build'][] = '_lb_related_articles_blocks_field_tags_after_build';
  }
  if (isset($element['field_article_type'])) {
    $element['field_article_type']['widget']['#after_build'][] = '_lb_related_articles_blocks_field_article_type_after_build';
  }
  if (isset($element['field_content_items'])) {
    $element['field_content_items']['widget']['#after_build'][] = '_lb_related_articles_blocks_field_content_items_after_build';
  }
  return $element;
}

/**
 * Custom '#after_build' callback for 'Locations' field.
 */
function _lb_related_articles_blocks_field_location_reference_after_build($element, FormStateInterface $form_state) {
  $element['#states'] = [
    'visible' => [
      [':input[name="settings[block_form][field_widget_type]"]' => [
        'value' => 'locations',
      ]],
      [':input[name="block_form[field_widget_type]"]' => [
        'value' => 'locations',
      ]],
    ],
  ];
  return $element;
}

/**
 * Custom '#after_build' callback for 'Tags' field.
 */
function _lb_related_articles_blocks_field_tags_after_build($element, FormStateInterface $form_state) {
  $element['#states'] = [
    'visible' => [
      [':input[name="settings[block_form][field_widget_type]"]' => [
        'value' => 'tags',
      ]],
      [':input[name="block_form[field_widget_type]"]' => [
        'value' => 'tags',
      ]],
    ],
  ];
  return $element;
}
/**
 * Custom '#after_build' callback for 'Article type' field.
 */
function _lb_related_articles_blocks_field_article_type_after_build($element, FormStateInterface $form_state) {
  $element['#states'] = [
    'visible' => [
      [':input[name="settings[block_form][field_widget_type]"]' => [
        'value' => 'article_type',
      ]],
      [':input[name="block_form[field_widget_type]"]' => [
        'value' => 'article_type',
      ]],
    ],
  ];
  $element['#options']['_none'] = t('- All -');
  return $element;
}
/**
 * Custom '#after_build' callback for 'Specified items' field.
 */
function _lb_related_articles_blocks_field_content_items_after_build($element, FormStateInterface $form_state) {
  $element['#states'] = [
    'visible' => [
      [':input[name="settings[block_form][field_widget_type]"]' => [
        'value' => 'manual',
      ]],
      [':input[name="block_form[field_widget_type]"]' => [
        'value' => 'manual',
      ]],
    ],
  ];
  return $element;
}

/**
 * Implements hook_form_BASE_FORM_ID_alter().
 */
function lb_related_articles_blocks_form_block_content_lb_related_articles_form_alter(&$form, FormStateInterface $form_state) {
  $bu = 0;
  $form['field_location_reference']['#states'] = [
    'visible' => [
      ':input[name="field_widget_type"]' => [
        'value' => 'locations',
      ],
    ],
  ];
  $form['field_tags']['#states'] = [
    'visible' => [
      ':input[name="field_widget_type"]' => [
        'value' => 'tags',
      ],
    ],
  ];
  $form['field_article_type']['#states'] = [
    'visible' => [
      ':input[name="field_widget_type"]' => [
        'value' => 'article_type',
      ],
    ],
  ];
  $form['field_content_items']['#states'] = [
    'visible' => [
      ':input[name="field_widget_type"]' => [
        'value' => 'manual',
      ],
    ],
  ];
}
